#!/usr/bin/bash

set -euo pipefail

# usage:
# $ ./diagnostic.sh <file_name>
# Example:
# $ ./diagnostic.sh TMCompiler/src/unittesting/unittesting.hpp

# .clang-tidy file generated by 
# $ clang-tidy -dump-config -checks=*,-llvm-header-guard,-fuchsia-trailing-return,-cppcoreguidelines-macro-usage,-fuchsia-statically-constructed-objects,-fuchsia-default-arguments-calls,-fuchsia-overloaded-operator,-cert-err58-cpp -- -std=c++14 > .clang-tidy

# reference: https://www.labri.fr/perso/fleury/posts/programming/using-clang-tidy-and-clang-format.html

# reason for not including specific checks:
# llvm-header-guard: Turns header guards into long names that show entire file path on my machine
# fuchsia-trailing-return: warns about trailing return types, when I want to use it
# fuchsia-statically-constructed-objects: forbids global objects, even though I do have global variables
# fuchsia-default-arguments-calls: forbids calling functions with default arguments
# fuchsia-overloaded-operator: forbids overloading operators like <<               what?? this isn't in the list
# cert-err58-cpp: warns about global variables with static storage that may throw an exception, even though I do use global variables
# cppcoreguidelines-macro-usage: forbids function-like macros, but I need it for logging and unittests

clang-tidy "$1" -config='' -header-filter=.* --quiet -- -std=c++14 -I.
