#!/usr/bin/bash

set -euo pipefail

# usage:
# $ ./diagnostic.sh <file_name>
# Example:
# $ ./diagnostic.sh TMCompiler/src/unittesting/unittesting.hpp

# .clang-tidy file generated by 
# $ clang-tidy -dump-config -checks=*,-llvm-header-guard,-fuchsia-trailing-return,-fuchsia-default-arguments-calls,-fuchsia-statically-constructed-objects,-fuchsia-default-arguments-declarations,-cert-err58-cpp,-hicpp-use-auto,-modernize-use-auto,-google-runtime-references,-cppcoreguidelines-macro-usage -- -std=c++14 > .clang-tidy

# reference: https://www.labri.fr/perso/fleury/posts/programming/using-clang-tidy-and-clang-format.html

clang-tidy "$1" -config='' -header-filter=.* --quiet -- -std=c++14 -I.
