# reference from https://gist.github.com/arslancharyev31/c48d18d8f917ffe217a0e23eb3535957

<token> ::= <whitespace>
		  | <line-comment>
		  | <block-comment>
		  | <keyword>
		  | <integer-constant>
		  | <boolean-constant>
		  | <identifier>
		  | <punctuator>

<whitespace> ::= "\s+"

# line-comments start with // and end with newline
<line-comment> ::= "//[^\n\r]+[\n\r]"

# block-comments start with /* and end with */. In between is (not */)
# every section either starts without a star, or it starts with a star followed
# by a non-star, or it is any number of stars and ends with */
# /\* matches /*
# (A|B)* matches A or B any number of times
# [^*]+ matches at least one character that is not *
# \*+[^/] matches at least one star, then a character that is not /
# \** matches 0 or more stars *
# \*/ matches */
<block-comment> ::= "/\*([^*]+|\*+[^/])*\**\*/"
<keyword> ::= "(void|int|bool|for|while|if|else|break|continue|return)"
<integer-constant> ::= "\d+"
<boolean-constant> ::= "(true|false)"
<identifier> ::= "[a-zA-Z][a-zA-Z0-9]*"
<punctuator> ::= "(\[|\]|\(|\)|\{|\}|\*|\+|-|!|/|%|<|>|\^|;|=|,|&|\|)"
