/**
 * Given the name of a JSON file generated by the compile program,
 * read in the Multi-Tape Turing Machine and simulate for a number of steps
 */

#include <iostream>

#include "TMCompiler/tm_definition/multi_tape_turing_machine.hpp"

int main(int argc, char* argv[]) {
	if(argc <= 1) {
		std::cout << "Please provide the name of a JSON file to read in" << std::endl;
		return -1;
	}

	// options...
	


}
